config/routes.rb
Perfdb::Application.routes.draw do
  resources :verticals
  resources :producers
  resources :general_managers
  resources :site_stats
  resources :site_data
  resources :site_datas
  resources :vertical_teams
  resources :authors
  resources :content_sources
  resources :content_types
  resources :views
  resources :articles
  resources :sites
  resources :editors

  
  match 'reports/sixty_day_articles/', :controller => 'articles', :action => 'sixty_day_articles'
  match 'sites/:id/reports/overview/:year/:month', :controller  => 'sites', :action => 'show_month'
  match 'sites/:id/reports/authors/:year/:month', :controller => 'sites', :action => 'monthly_author_report'
  match 'sites/:id/reports/content/:year/:month', :controller => 'sites', :action => 'monthly_content'
  match '/models', :controller => 'sites', :action => 'perfdb_models'
  match '/', :controller => 'sites', :action => 'app_index'
  match 'sites/:id/reports/content', :controller => 'sites', :action => 'period_content'
  
  
  match 'sites/monthly_content_type_report/:id/:year/:month/', :controller  => 'sites', :action => 'monthly_content_type'
  match 'sites/monthly_content_source_report/:id/:year/:month/', :controller  => 'sites', :action => 'monthly_content_source'
  match 'content_types/:year/:month', :controller => 'content_types', :action => 'period_view'
  match 'site/:shortname/', :controller => 'sites', :action => 'show_site'
  match 'combined_content/', :controller => 'content_types', :action => 'combined_content'
  match 'combined_content/:year/:month', :controller => 'content_types', :action => 'combined_content_month_view'
  match 'articles/network_top_articles/:year/:month', :controller => 'articles', :action => 'network_top_articles'
  match 'vertical_teams/:id/:year/:month', :controller => 'vertical_teams', :action => 'show_month'
  match 'reports/:id/content_source', :controller => 'sites', :action => 'site_content_source'
  match 'reports/:id/content_type', :controller => 'sites', :action => 'site_content_type'
  match 'reports/content_source/:id/:year/:month', :controller => 'sites', :action => 'monthly_site_content_source'
  match 'reports/content_type/:id/:year/:month', :controller => 'sites', :action => 'monthly_site_content_type'
  match 'reports/network/content/:year/:month', :controller => 'content_types', :action => 'network_period_view'
  

end

app/models/vertical.rb
class Vertical < ActiveRecord::Base
  
  has_many :sites
  has_many :articles, :through => :sites
end

app/controllers/verticals_controller.rb
class VerticalsController < ApplicationController
  # GET /verticals
  # GET /verticals.xml
  def index
    @verticals = Vertical.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @verticals }
    end
  end

  # GET /verticals/1
  # GET /verticals/1.xml
  def show
    @vertical = Vertical.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @vertical }
    end
  end

  # GET /verticals/new
  # GET /verticals/new.xml
  def new
    @vertical = Vertical.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @vertical }
    end
  end

  # GET /verticals/1/edit
  def edit
    @vertical = Vertical.find(params[:id])
  end

  # POST /verticals
  # POST /verticals.xml
  def create
    @vertical = Vertical.new(params[:vertical])

    respond_to do |format|
      if @vertical.save
        format.html { redirect_to(@vertical, :notice => 'Vertical was successfully created.') }
        format.xml  { render :xml => @vertical, :status => :created, :location => @vertical }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @vertical.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /verticals/1
  # PUT /verticals/1.xml
  def update
    @vertical = Vertical.find(params[:id])

    respond_to do |format|
      if @vertical.update_attributes(params[:vertical])
        format.html { redirect_to(@vertical, :notice => 'Vertical was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @vertical.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /verticals/1
  # DELETE /verticals/1.xml
  def destroy
    @vertical = Vertical.find(params[:id])
    @vertical.destroy

    respond_to do |format|
      format.html { redirect_to(verticals_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/verticals_helper.rb
module VerticalsHelper
end

app/views/verticals/_form.html.erb
<%= form_for(@vertical) do |f| %>
  <% if @vertical.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vertical.errors.count, "error") %> prohibited this vertical from being saved:</h2>

      <ul>
      <% @vertical.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :general_manager_id %><br />
    <%= f.text_field :general_manager_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/verticals/edit.html.erb
<h1>Editing vertical</h1>

<%= render 'form' %>

<%= link_to 'Show', @vertical %> |
<%= link_to 'Back', verticals_path %>

app/views/verticals/index.html.erb
<h1>Listing verticals</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>General manager</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @verticals.each do |vertical| %>
  <tr>
    <td><%= vertical.id %></td>
    <td><%= vertical.name %></td>
    <td><%= vertical.general_manager_id %></td>
    <td><%= link_to 'Show', vertical %></td>
    <td><%= link_to 'Edit', edit_vertical_path(vertical) %></td>
    <td><%= link_to 'Destroy', vertical, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Vertical', new_vertical_path %>

app/views/verticals/new.html.erb
<h1>New vertical</h1>

<%= render 'form' %>

<%= link_to 'Back', verticals_path %>

app/views/verticals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @vertical.id %>
</p>

<p>
  <b>Name:</b>
  <%= @vertical.name %>
</p>

<p>
  <b>General manager:</b>
  <%= @vertical.general_manager_id %>
</p>


<%= link_to 'Edit', edit_vertical_path(@vertical) %> |
<%= link_to 'Back', verticals_path %>