config/routes.rb
Perfdb::Application.routes.draw do
  resources :verticals
  resources :producers
  resources :general_managers
  resources :site_stats
  resources :site_data
  resources :site_datas
  resources :vertical_teams
  resources :authors
  resources :content_sources
  resources :content_types
  resources :views
  resources :articles
  resources :sites
  resources :editors

  
  match 'reports/sixty_day_articles/', :controller => 'articles', :action => 'sixty_day_articles'
  match 'sites/:id/reports/overview/:year/:month', :controller  => 'sites', :action => 'show_month'
  match 'sites/:id/reports/authors/:year/:month', :controller => 'sites', :action => 'monthly_author_report'
  match 'sites/:id/reports/content/:year/:month', :controller => 'sites', :action => 'monthly_content'
  match '/models', :controller => 'sites', :action => 'perfdb_models'
  match '/', :controller => 'sites', :action => 'app_index'
  match 'sites/:id/reports/content', :controller => 'sites', :action => 'period_content'
  
  
  match 'sites/monthly_content_type_report/:id/:year/:month/', :controller  => 'sites', :action => 'monthly_content_type'
  match 'sites/monthly_content_source_report/:id/:year/:month/', :controller  => 'sites', :action => 'monthly_content_source'
  match 'content_types/:year/:month', :controller => 'content_types', :action => 'period_view'
  match 'site/:shortname/', :controller => 'sites', :action => 'show_site'
  match 'combined_content/', :controller => 'content_types', :action => 'combined_content'
  match 'combined_content/:year/:month', :controller => 'content_types', :action => 'combined_content_month_view'
  match 'articles/network_top_articles/:year/:month', :controller => 'articles', :action => 'network_top_articles'
  match 'vertical_teams/:id/:year/:month', :controller => 'vertical_teams', :action => 'show_month'
  match 'reports/:id/content_source', :controller => 'sites', :action => 'site_content_source'
  match 'reports/:id/content_type', :controller => 'sites', :action => 'site_content_type'
  match 'reports/content_source/:id/:year/:month', :controller => 'sites', :action => 'monthly_site_content_source'
  match 'reports/content_type/:id/:year/:month', :controller => 'sites', :action => 'monthly_site_content_type'
  match 'reports/network/content/:year/:month', :controller => 'content_types', :action => 'network_period_view'
  

end

app/models/site_stat.rb
class SiteStat < ActiveRecord::Base
  belongs_to :site
  serialize :preferences
  has_many :social_sites
end

app/controllers/site_stats_controller.rb
class SiteStatsController < ApplicationController
  # GET /site_stats
  # GET /site_stats.xml
  def index
    @site_stats = SiteStat.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @site_stats }
    end
  end

  # GET /site_stats/1
  # GET /site_stats/1.xml
  def show
    @site_stat = SiteStat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @site_stat }
    end
  end

  # GET /site_stats/new
  # GET /site_stats/new.xml
  def new
    @site_stat = SiteStat.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @site_stat }
    end
  end

  # GET /site_stats/1/edit
  def edit
    @site_stat = SiteStat.find(params[:id])
  end

  # POST /site_stats
  # POST /site_stats.xml
  def create
    @site_stat = SiteStat.new(params[:site_stat])

    respond_to do |format|
      if @site_stat.save
        format.html { redirect_to(@site_stat, :notice => 'Site stat was successfully created.') }
        format.xml  { render :xml => @site_stat, :status => :created, :location => @site_stat }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @site_stat.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /site_stats/1
  # PUT /site_stats/1.xml
  def update
    @site_stat = SiteStat.find(params[:id])

    respond_to do |format|
      if @site_stat.update_attributes(params[:site_stat])
        format.html { redirect_to(@site_stat, :notice => 'Site stat was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @site_stat.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /site_stats/1
  # DELETE /site_stats/1.xml
  def destroy
    @site_stat = SiteStat.find(params[:id])
    @site_stat.destroy

    respond_to do |format|
      format.html { redirect_to(site_stats_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/site_stats_helper.rb
module SiteStatsHelper
end

app/views/site_stats/_form.html.erb
<%= form_for(@site_stat) do |f| %>
  <% if @site_stat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site_stat.errors.count, "error") %> prohibited this site_stat from being saved:</h2>

      <ul>
      <% @site_stat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :site_id %><br />
    <%= f.text_field :site_id %>
  </div>
  <div class="field">
    <%= f.label :month %><br />
    <%= f.date_select :month %>
  </div>
  <div class="field">
    <%= f.label :pageviews %><br />
    <%= f.text_field :pageviews %>
  </div>
  <div class="field">
    <%= f.label :bounces %><br />
    <%= f.text_field :bounces %>
  </div>
  <div class="field">
    <%= f.label :revenue %><br />
    <%= f.text_field :revenue %>
  </div>
  <div class="field">
    <%= f.label :bouncerate %><br />
    <%= f.text_field :bouncerate %>
  </div>
  <div class="field">
    <%= f.label :bounces %><br />
    <%= f.text_field :bounces %>
  </div>
  <div class="field">
    <%= f.label :unique_pageviews %><br />
    <%= f.text_field :unique_pageviews %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/site_stats/edit.html.erb
<h1>Editing site_stat</h1>

<%= render 'form' %>

<%= link_to 'Show', @site_stat %> |
<%= link_to 'Back', site_stats_path %>

app/views/site_stats/index.html.erb
<h1>Listing site_stats</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Site</th>
    <th>Month</th>
    <th>Pageviews</th>
    <th>Bounces</th>
    <th>Revenue</th>
    <th>Bouncerate</th>
    <th>Bounces</th>
    <th>Unique pageviews</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @site_stats.each do |site_stat| %>
  <tr>
    <td><%= site_stat.id %></td>
    <td><%= site_stat.site_id %></td>
    <td><%= site_stat.month %></td>
    <td><%= site_stat.pageviews %></td>
    <td><%= site_stat.bounces %></td>
    <td><%= site_stat.revenue %></td>
    <td><%= site_stat.bouncerate %></td>
    <td><%= site_stat.bounces %></td>
    <td><%= site_stat.unique_pageviews %></td>
    <td><%= link_to 'Show', site_stat %></td>
    <td><%= link_to 'Edit', edit_site_stat_path(site_stat) %></td>
    <td><%= link_to 'Destroy', site_stat, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Site stat', new_site_stat_path %>

app/views/site_stats/new.html.erb
<h1>New site_stat</h1>

<%= render 'form' %>

<%= link_to 'Back', site_stats_path %>

app/views/site_stats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @site_stat.id %>
</p>

<p>
  <b>Site:</b>
  <%= @site_stat.site_id %>
</p>

<p>
  <b>Month:</b>
  <%= @site_stat.month %>
</p>

<p>
  <b>Pageviews:</b>
  <%= @site_stat.pageviews %>
</p>

<p>
  <b>Bounces:</b>
  <%= @site_stat.bounces %>
</p>

<p>
  <b>Revenue:</b>
  <%= @site_stat.revenue %>
</p>

<p>
  <b>Bouncerate:</b>
  <%= @site_stat.bouncerate %>
</p>

<p>
  <b>Bounces:</b>
  <%= @site_stat.bounces %>
</p>

<p>
  <b>Unique pageviews:</b>
  <%= @site_stat.unique_pageviews %>
</p>


<%= link_to 'Edit', edit_site_stat_path(@site_stat) %> |
<%= link_to 'Back', site_stats_path %>