config/routes.rb
Perfdb::Application.routes.draw do
  resources :verticals
  resources :producers
  resources :general_managers
  resources :site_stats
  resources :site_data
  resources :site_datas
  resources :vertical_teams
  resources :authors
  resources :content_sources
  resources :content_types
  resources :views
  resources :articles
  resources :sites
  resources :editors

  
  match 'reports/sixty_day_articles/', :controller => 'articles', :action => 'sixty_day_articles'
  match 'sites/:id/reports/overview/:year/:month', :controller  => 'sites', :action => 'show_month'
  match 'sites/:id/reports/authors/:year/:month', :controller => 'sites', :action => 'monthly_author_report'
  match 'sites/:id/reports/content/:year/:month', :controller => 'sites', :action => 'monthly_content'
  match '/models', :controller => 'sites', :action => 'perfdb_models'
  match '/', :controller => 'sites', :action => 'app_index'
  match 'sites/:id/reports/content', :controller => 'sites', :action => 'period_content'
  
  
  match 'sites/monthly_content_type_report/:id/:year/:month/', :controller  => 'sites', :action => 'monthly_content_type'
  match 'sites/monthly_content_source_report/:id/:year/:month/', :controller  => 'sites', :action => 'monthly_content_source'
  match 'content_types/:year/:month', :controller => 'content_types', :action => 'period_view'
  match 'site/:shortname/', :controller => 'sites', :action => 'show_site'
  match 'combined_content/', :controller => 'content_types', :action => 'combined_content'
  match 'combined_content/:year/:month', :controller => 'content_types', :action => 'combined_content_month_view'
  match 'articles/network_top_articles/:year/:month', :controller => 'articles', :action => 'network_top_articles'
  match 'vertical_teams/:id/:year/:month', :controller => 'vertical_teams', :action => 'show_month'
  match 'reports/:id/content_source', :controller => 'sites', :action => 'site_content_source'
  match 'reports/:id/content_type', :controller => 'sites', :action => 'site_content_type'
  match 'reports/content_source/:id/:year/:month', :controller => 'sites', :action => 'monthly_site_content_source'
  match 'reports/content_type/:id/:year/:month', :controller => 'sites', :action => 'monthly_site_content_type'
  match 'reports/network/content/:year/:month', :controller => 'content_types', :action => 'network_period_view'
  

end

app/controllers/producers_controller.rb
class ProducersController < ApplicationController
  # GET /producers
  # GET /producers.xml
  def index
    @producers = Producer.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @producers }
    end
  end

  # GET /producers/1
  # GET /producers/1.xml
  def show
    @producer = Producer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @producer }
    end
  end

  # GET /producers/new
  # GET /producers/new.xml
  def new
    @producer = Producer.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @producer }
    end
  end

  # GET /producers/1/edit
  def edit
    @producer = Producer.find(params[:id])
  end

  # POST /producers
  # POST /producers.xml
  def create
    @producer = Producer.new(params[:producer])

    respond_to do |format|
      if @producer.save
        format.html { redirect_to(@producer, :notice => 'Producer was successfully created.') }
        format.xml  { render :xml => @producer, :status => :created, :location => @producer }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @producer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /producers/1
  # PUT /producers/1.xml
  def update
    @producer = Producer.find(params[:id])

    respond_to do |format|
      if @producer.update_attributes(params[:producer])
        format.html { redirect_to(@producer, :notice => 'Producer was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @producer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /producers/1
  # DELETE /producers/1.xml
  def destroy
    @producer = Producer.find(params[:id])
    @producer.destroy

    respond_to do |format|
      format.html { redirect_to(producers_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/producers_helper.rb
module ProducersHelper
end

app/views/producers/_form.html.erb
<%= form_for(@producer) do |f| %>
  <% if @producer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@producer.errors.count, "error") %> prohibited this producer from being saved:</h2>

      <ul>
      <% @producer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_area :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/producers/edit.html.erb
<h1>Editing producer</h1>

<%= render 'form' %>

<%= link_to 'Show', @producer %> |
<%= link_to 'Back', producers_path %>

app/views/producers/index.html.erb
<h1>Listing producers</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @producers.each do |producer| %>
  <tr>
    <td><%= producer.id %></td>
    <td><%= producer.name %></td>
    <td><%= producer.email %></td>
    <td><%= link_to 'Show', producer %></td>
    <td><%= link_to 'Edit', edit_producer_path(producer) %></td>
    <td><%= link_to 'Destroy', producer, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Producer', new_producer_path %>

app/views/producers/new.html.erb
<h1>New producer</h1>

<%= render 'form' %>

<%= link_to 'Back', producers_path %>

app/views/producers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @producer.id %>
</p>

<p>
  <b>Name:</b>
  <%= @producer.name %>
</p>

<p>
  <b>Email:</b>
  <%= @producer.email %>
</p>


<%= link_to 'Edit', edit_producer_path(@producer) %> |
<%= link_to 'Back', producers_path %>