config/routes.rb
Perfdb::Application.routes.draw do
  resources :verticals
  resources :producers
  resources :general_managers
  resources :site_stats
  resources :site_data
  resources :site_datas
  resources :vertical_teams
  resources :authors
  resources :content_sources
  resources :content_types
  resources :views
  resources :articles
  resources :sites
  resources :editors

  
  match 'reports/sixty_day_articles/', :controller => 'articles', :action => 'sixty_day_articles'
  match 'sites/:id/reports/overview/:year/:month', :controller  => 'sites', :action => 'show_month'
  match 'sites/:id/reports/authors/:year/:month', :controller => 'sites', :action => 'monthly_author_report'
  match 'sites/:id/reports/content/:year/:month', :controller => 'sites', :action => 'monthly_content'
  match '/models', :controller => 'sites', :action => 'perfdb_models'
  match '/', :controller => 'sites', :action => 'app_index'
  match 'sites/:id/reports/content', :controller => 'sites', :action => 'period_content'
  
  
  match 'sites/monthly_content_type_report/:id/:year/:month/', :controller  => 'sites', :action => 'monthly_content_type'
  match 'sites/monthly_content_source_report/:id/:year/:month/', :controller  => 'sites', :action => 'monthly_content_source'
  match 'content_types/:year/:month', :controller => 'content_types', :action => 'period_view'
  match 'site/:shortname/', :controller => 'sites', :action => 'show_site'
  match 'combined_content/', :controller => 'content_types', :action => 'combined_content'
  match 'combined_content/:year/:month', :controller => 'content_types', :action => 'combined_content_month_view'
  match 'articles/network_top_articles/:year/:month', :controller => 'articles', :action => 'network_top_articles'
  match 'vertical_teams/:id/:year/:month', :controller => 'vertical_teams', :action => 'show_month'
  match 'reports/:id/content_source', :controller => 'sites', :action => 'site_content_source'
  match 'reports/:id/content_type', :controller => 'sites', :action => 'site_content_type'
  match 'reports/content_source/:id/:year/:month', :controller => 'sites', :action => 'monthly_site_content_source'
  match 'reports/content_type/:id/:year/:month', :controller => 'sites', :action => 'monthly_site_content_type'
  match 'reports/network/content/:year/:month', :controller => 'content_types', :action => 'network_period_view'
  

end

app/controllers/general_managers_controller.rb
class GeneralManagersController < ApplicationController
  # GET /general_managers
  # GET /general_managers.xml
  def index
    @general_managers = GeneralManager.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @general_managers }
    end
  end

  # GET /general_managers/1
  # GET /general_managers/1.xml
  def show
    @general_manager = GeneralManager.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @general_manager }
    end
  end

  # GET /general_managers/new
  # GET /general_managers/new.xml
  def new
    @general_manager = GeneralManager.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @general_manager }
    end
  end

  # GET /general_managers/1/edit
  def edit
    @general_manager = GeneralManager.find(params[:id])
  end

  # POST /general_managers
  # POST /general_managers.xml
  def create
    @general_manager = GeneralManager.new(params[:general_manager])

    respond_to do |format|
      if @general_manager.save
        format.html { redirect_to(@general_manager, :notice => 'General manager was successfully created.') }
        format.xml  { render :xml => @general_manager, :status => :created, :location => @general_manager }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @general_manager.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /general_managers/1
  # PUT /general_managers/1.xml
  def update
    @general_manager = GeneralManager.find(params[:id])

    respond_to do |format|
      if @general_manager.update_attributes(params[:general_manager])
        format.html { redirect_to(@general_manager, :notice => 'General manager was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @general_manager.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /general_managers/1
  # DELETE /general_managers/1.xml
  def destroy
    @general_manager = GeneralManager.find(params[:id])
    @general_manager.destroy

    respond_to do |format|
      format.html { redirect_to(general_managers_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/general_managers_helper.rb
module GeneralManagersHelper
end

app/views/general_managers/_form.html.erb
<%= form_for(@general_manager) do |f| %>
  <% if @general_manager.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@general_manager.errors.count, "error") %> prohibited this general_manager from being saved:</h2>

      <ul>
      <% @general_manager.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_area :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/general_managers/edit.html.erb
<h1>Editing general_manager</h1>

<%= render 'form' %>

<%= link_to 'Show', @general_manager %> |
<%= link_to 'Back', general_managers_path %>

app/views/general_managers/index.html.erb
<h1>Listing general_managers</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @general_managers.each do |general_manager| %>
  <tr>
    <td><%= general_manager.id %></td>
    <td><%= general_manager.name %></td>
    <td><%= general_manager.email %></td>
    <td><%= link_to 'Show', general_manager %></td>
    <td><%= link_to 'Edit', edit_general_manager_path(general_manager) %></td>
    <td><%= link_to 'Destroy', general_manager, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New General manager', new_general_manager_path %>

app/views/general_managers/new.html.erb
<h1>New general_manager</h1>

<%= render 'form' %>

<%= link_to 'Back', general_managers_path %>

app/views/general_managers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @general_manager.id %>
</p>

<p>
  <b>Name:</b>
  <%= @general_manager.name %>
</p>

<p>
  <b>Email:</b>
  <%= @general_manager.email %>
</p>


<%= link_to 'Edit', edit_general_manager_path(@general_manager) %> |
<%= link_to 'Back', general_managers_path %>